### ISSUE TITLE
Can We Run This SOE With A Network With Weight Filters

### ISSUE THREAD

**Issue by Behseini** [nicogis/Geometric-Network-Utility-SOE#2]
I just wonder if we can run this .soe file with a Network which has enabled with Weight Filters? For example in case of having a request like this

```
# Process: Trace Geometric Network
arcpy.TraceGeometricNetwork_management(WaterNet, WaterNet2, Flag, "TRACE_UPSTREAM", "", "", "Filter_Factor", "Filter_Factor", "", "NO_TRACE_ENDS", "", "", "", "AS_IS", "Filter_Factor", "Filter_Factor", "3", "AS_IS")
```
how can I apply the weight in following request?

```
http://xxx/arcgis/rest/services/Electric/MapServer/exts/GeometricNetworkUtility/GeometricNetworks/1/TraceNetwork?
traceSolverType=TRACE_DOWNSTREAM
&flowMethod=
&flowElements=
&edgeFlags=
&junctionFlags=
&edgeBarriers=
&junctionBarriers=
&outFields=
&maxTracedFeatures=
&tolerance=
&traceIndeterminateFlow=
&shortestPathObjFn=
&disableLayers=
&junctionWeight=
&fromToEdgeWeight=
&toFromEdgeWeight=
&junctionFilterWeight=
&junctionFilterRanges=
&junctionFilterNotOperator=
&fromToEdgeFilterWeight=
&toFromEdgeFilterWeight=
&edgeFilterRanges=
&edgeFilterNotOperator=
&f=html
```
Thanks

**Comment by nicogis** [comment]
Yes
        junctionWeight = "TestJunction";
        fromToEdgeWeight = "LengthLine";
        toFromEdgeWeight = "LengthLine";
        junctionFilterWeight = "TestJunction";
        junctionFilterRanges = "0-700";
        junctionFilterNotOperator = false;
        fromToEdgeFilterWeight = "LengthLine";
        toFromEdgeFilterWeight = "LengthLine";
        edgeFilterRanges = "0-400";
        edgeFilterNotOperator = false;

see help http://sit2.sistemigis.it/sit/rest/services/Demo/GeometricNetwork/MapServer/exts/GeometricNetworkUtility/Help

**Comment by Behseini** [comment]
Thanks for reply but this is not working on this example!
I am using ESRI provided [Electric Facility Data](http://solutions.arcgis.com/utilities/electric/help/electric-facility-maps/) 
I have set up the network like 

![network](https://user-images.githubusercontent.com/4685676/31954195-c25b0c54-b899-11e7-87b5-adb7099bc493.png)

The Bitgate Value been set up at Geodatabase Domain like
![domain](https://user-images.githubusercontent.com/4685676/31954244-f2857932-b899-11e7-912b-86cf0e98015f.png)

and it is functioning and implementing well on ArcMap session on Geometric Network Analysis Options (Tested at ArcMap and working properly)

![networkoptions](https://user-images.githubusercontent.com/4685676/31954541-bfb97048-b89a-11e7-83ae-7bf48652c87e.png)

But it return none when I Pass following set in the SEO interface

![soe](https://user-images.githubusercontent.com/4685676/31955031-0ae97224-b89c-11e7-8984-398b71d484f9.png)

I already check exact Junction Flag on ArcMap and it is tracing and returning some values based on **Phase A (4)** but I am not getting any thing here! Can you please let me know what I am doing wrong?

```
            junctionWeight= 'PhaseBitgate';
            fromToEdgeWeight= 'PhaseBitgate';
            toFromEdgeWeight= 'PhaseBitgate';
            junctionFilterWeight= 'PhaseBitgate';
            junctionFilterRanges= 4;
            junctionFilterNotOperator= false;
            fromToEdgeFilterWeight= 'PhaseBitgate';
            toFromEdgeFilterWeight= 'PhaseBitgate';
            edgeFilterRanges= 4;
            edgeFilterNotOperator 	= false;
```

Thanks
