### ISSUE TITLE
Not Getting Result Back On Bitgate Weights

### ISSUE THREAD

**Issue by Behseini** [nicogis/Geometric-Network-Utility-SOE#3]
Not Getting Result Back On Bitgate Weights

**Comment by nicogis** [comment]
do you see the definition Bitgate Weights in rest 
(syntax: http://hostname/arcgis/rest/services/myservice/MapServer/exts/GeometricNetworkUtility/GeometricNetworks/1 )  ?
Have you message in log arcgis server ?

**Comment by nicogis** [comment]
do you see the definition Bitgate Weights in rest 
(syntax: http://hostname/arcgis/rest/services/myservice/MapServer/exts/GeometricNetworkUtility/GeometricNetworks/1 )  ?
Have you message in log arcgis server ?

**Comment by nicogis** [comment]
do you see the definition Bitgate Weights in rest 
(syntax: hostname/arcgis/rest/services/myservice/MapServer/exts/GeometricNetworkUtility/GeometricNetworks/1 )  ?
Have you message in log arcgis server ?

**Comment by nicogis** [comment]
do you see the definition Bitgate Weights in rest 
(syntax: hostname/arcgis/rest/services/myservice/MapServer/exts/GeometricNetworkUtility/GeometricNetworks/1 )  ?
Have you message in log arcgis server ?

**Comment by Behseini** [comment]
Thanks for reply Domenico, 
Here is a screen shot of what I have in the 
(syntax: http://hostname/arcgis/rest/services/myservice/MapServer/exts/GeometricNetworkUtility/GeometricNetworks/1 ) ?

![trace](https://user-images.githubusercontent.com/4685676/32570339-b2a4c0ee-c478-11e7-8468-34f8ca40e5f6.png)


I am also adding some screenshots of what I have in the network. I am basically using ESRI Electric Facility Map. The Network Weight is in Bitgate formats like 
![network](https://user-images.githubusercontent.com/4685676/32579973-1214782a-c498-11e7-97c0-2a31fe15947f.png)

which has been set up based on Geodatabase Subtype and Domain setup 

![domain](https://user-images.githubusercontent.com/4685676/32580047-6aa47dc8-c498-11e7-9e1c-729a36b6453a.png)

The Network is tracing and functioning properly in ArcMap on passing Bitgates values. For Example the combination of '0,4,2,1' is tracing only 'ABC' phases.

![networkoptions](https://user-images.githubusercontent.com/4685676/32580329-92e3c9a0-c499-11e7-8c6a-6a57927a9804.png)

but when I try to pass the weights like '0,4,2,1' on SOE like 

![soe2](https://user-images.githubusercontent.com/4685676/32580514-80ca7628-c49a-11e7-8a00-be02829b9f93.png)

I am getting Not Valid ' code 400 0,4,2,1 not valid (BitGateSize)' error message

**Comment by nicogis** [comment]
Ok I have understood the problem: for bitgate I don't manage the value in this format with comma

**Comment by Behseini** [comment]
~~_Thanks again but when I try to pass like 1 or 2 or 3 or 4 or 5 or 6 or 7 I am getting this error
error:
code: 500
message: Exception from HRESULT: 0x80040215_~~

**Comment by Behseini** [comment]
Please dismiss previous comment looks like it was spatial reference issue. Now, after fixing it, I am getting:


**edges: None
junctions: None
flagsNotFound: None
barriersNotFound: None**

on passing any of  1 or 2 or 3 or 4 or 5 or 6 or 7 as weights. 
I tried this for both flowMethod "esriFMDownstream" and "esriFMUpstream" on each of junctionFlags or edgeBarriers (with different inputs) but the result is always None!

**Comment by nicogis** [comment]
I have fixed: https://github.com/nicogis/Geometric-Network-Utility-SOE/releases/tag/v1.3

**Comment by Behseini** [comment]
Great! Thanks a lots this is working now.
