### ISSUE TITLE
No Return on Cominiatin Ranges In Bitgate

### ISSUE THREAD

**Issue by Behseini** [nicogis/Geometric-Network-Utility-SOE#4]
Hi Domenico,
Thanks for updating the V. 1.3 of Geometric Network Utility SOE. As we discussed this already, this version in working fine on some scenarios like when we pass only a weight like `04`  or `0,4` . The SOE returning correct filtered values base on weight but when I pass a combinations like `0421` or `0,4,2,1` it return None! 
I have already test a Junction with ABC wight range which is connected to many edges with ABC ranges in ArcMap and getting proper result back there but same Flag on SOE just returns None.

Here is a list of all possible filter weight ranges in ESRI Electric  Facility map. As you can see SOE is qorking on single range but not on cominations

![bitgates](https://user-images.githubusercontent.com/4685676/32927747-5b4b9250-cb03-11e7-96f0-b85cb74008bc.png)

**Comment by nicogis** [comment]
Where I can donwload ESRI Electric Facility map geometric network so I can test this case ?
if you set 6 for ab or 5 for ac or 3 for bc or 7 for abc runs ok ?

**Comment by Behseini** [comment]
The Original Data are available at This Directory From ESRI
[ESRI Electric Facility Map](http://solutions.arcgis.com/utilities/electric/help/electric-facility-maps/)
Here is the the Web Mercator Converted with Geometric Network which I am using:
[Web Mercator With Geometric Network](http://renewablestoolbox.ca/GISData/Data.zip)

I also tried to debug the v1.3 source code but ArcGIS Server keeps complaining on `**ClassFactory cannot supply requested class**` error when I try to enable the SOE on the service or even on publishing new service! I am sure I have install the .Net supports on ArcGIS Server installation but couldn't figure it out why this is happening?!

**Comment by nicogis** [comment]
try see if you have binded library Esri correctly in vs. They must not copied in bin
if you set for weight 6 for ab or 5 for ac or 3 for bc or 7 for abc runs ok ?

**Comment by Behseini** [comment]
Well, I didn't try with any of 6 or 5 or 3 combinations but for sure for 7 which is (0,4,2,1) I am not getting back any thing.

**Comment by nicogis** [comment]
Ok I try with your data for problem

**Comment by Behseini** [comment]
Thanks

**Comment by Behseini** [comment]
Hi Domenico,
Did you have any chance to take a look at the submitted data set? 
Thanks,

**Comment by nicogis** [comment]
No I hope in this week
Bye

**Comment by nicogis** [comment]
here there is your sample data published https://demo.sistemigis.it/server/rest/services/ENetNADPDWeb/MapServer
What's the request with problem ?
