### ISSUE TITLE
ArcGIS Server Error ClassFactory cannot supply requested class with SOE

### ISSUE THREAD

**Issue by Behseini** [nicogis/Geometric-Network-Utility-SOE#5]
Hi,
sorry to adding this as a new Issue but I thought it is better to separate from last posted issue. Using VS 2015 Community with ArcGIS 10.4.1 with added ArcObjects SDK for NE Framework 1041_151832, I am able to Build , Clean and Rebuild the project without any error!
Here is solution explorer window

![so](https://user-images.githubusercontent.com/4685676/32957891-c4bce568-cb71-11e7-9658-f1b91a96ffe0.png)
 
As you can see all Assemblies already listed on `Add ArcGIS Reference` Window

![so2](https://user-images.githubusercontent.com/4685676/32957949-ed7a98c4-cb71-11e7-8f03-fe7521ac4d8f.png)

but when ever I try to enable an existing server with uploaded SOE or Publish new service  I am getting this error

![5](https://user-images.githubusercontent.com/4685676/32958337-00719f4e-cb73-11e7-9a49-7cf88ed7dfd1.png)

Here are the Project Property Windows

![so3](https://user-images.githubusercontent.com/4685676/32958178-8a883752-cb72-11e7-96b3-9b1c78d1dbf9.png)

![so4](https://user-images.githubusercontent.com/4685676/32958185-8e526736-cb72-11e7-986f-2e4e54c33298.png)
Here the IIS Application pools window

![iis](https://user-images.githubusercontent.com/4685676/32958889-a5c047c4-cb74-11e7-8925-ac828712e462.png)

and this the output of VS console

````1>------ Rebuild All started: Project: Studioat.ArcGis.Soe.Rest.GeometricNetworkUtility, Configuration: Debug Any CPU ------
1>  Studioat.ArcGis.Soe.Rest.GeometricNetworkUtility -> C:\Users\me\Desktop\Geometric-Network-Utility-SOE-1.3\bin\Debug\Studioat.ArcGis.Soe.Rest.GeometricNetworkUtility.dll
1>C:\Program Files (x86)\MSBuild\ESRI\ESRI.ArcGIS.Server.SDK.targets(41,5): warning : The 'TargetVersion '10.5' specified in the AddInPackage element is invalid -  The value is invalid according to the version of ArcGIS assemblies the project references - The value should be '10.4'
1>C:\Program Files (x86)\MSBuild\ESRI\ESRI.ArcGIS.Server.SDK.targets(41,5): warning : The project will continue to compile but the generated add-in may either fail to register or load properly in the ArcGIS application at runtime.
1>  Successfully created Add-in "Studioat.ArcGis.Soe.Rest.GeometricNetworkUtility" ->  'C:\Users\me\Desktop\Geometric-Network-Utility-SOE-1.3\bin\Debug\Studioat.ArcGis.Soe.Rest.GeometricNetworkUtility.soe'.
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ========== ````

**Comment by nicogis** [comment]
in https://github.com/nicogis/Geometric-Network-Utility-SOE/blob/4f2299c56729f716c5313c77ba50e1856192ac5f/Properties/AssemblyInfo.cs#L50
change with 10.4 because I have compiled with 10.5

**Comment by Behseini** [comment]
Great thanks it fixed now
