### ISSUE TITLE
How to get LayerName while Tracing geometric network 

### ISSUE THREAD

**Issue by Yamraaj12** [nicogis/Geometric-Network-Utility-SOE#8]
Hi Sir,

We are not able to get either layername nor the displayFieldName while tracing using above SOE in geometric network.

Any help or guidance will be fruitful of us in any circumstance.

Regards,
Sunny kumar

**Comment by nicogis** [comment]
here https://github.com/nicogis/Geometric-Network-Utility-SOE/blob/4f2299c56729f716c5313c77ba50e1856192ac5f/GeometricNetwork.cs#L257 from featureclass and filter of trace I create a recordset from every featureclass of trace that then I serialize in json so you can here add extra info that you need
