### ISSUE TITLE
Samples Do Not Work

### ISSUE THREAD

**Issue by arniechan2019** [nicogis/Geometric-Network-Utility-SOE#9]
Hi Domenico Ciavarella, @nicogis 
I have been trying to use your samples and they do not work
https://sit2.sistemigis.it/js/GeometricNetworkStream/
is the service down ?
Also, I do not see the data and  client in the samples folder as mentioned in the documentation.
Can you please upload the sample data and client code ?

Regards
Charnie

**Comment by nicogis** [comment]
Here you can download data and client: 
https://github.com/nicogis/Geometric-Network-Utility-SOE/releases/tag/v1.3

Yes, service is down. Now it's available.
Thank you
